# This is a basic workflow to help you get started with Actions

name: CI

on:

  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  ci:
    name: Integracion Continua
    runs-on: ubuntu-latest

    steps:

      - name: Descargar Codigo #Descarga el contenido del repositorio
        uses: actions/checkout@v4 # Checkout v4: accion oficial de github para descargar el codigo fuente del repositorio en el que se ejecuta el flujo del trabajo

      - name: Configurar python #Configura la version de Python que se utilizara en el flujo de trabajo 
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Validar sintaxis de python
        run: python -m py_compile app.py

      - name: Ejecutar pruebas básicas
        run: |
          python -c "from app import crear_servidor; print('Codigo Valido')"

      


